### ISSUE TITLE
[suggestion] Shoulder-swapping.

### ISSUE THREAD

**Issue by DravenXD** [killfrenzy96/LCThirdPerson#4]
Amazing mod. I've been using 3rdperson by verity for a long time and was interested in an upgrade and I can confidently say that you've delivered!
I am using a character that has wings on their back, so I have to offset the camera far to the right, but unfortunately, this means that it is really hard to interact with stuff on my left side (especially in corridors). And so, I would like to humbly request a shoulder-swapping feature, similar to Metal Gear.

Thank you for the mod, cheers!

**Comment by killfrenzy96** [comment]
That's a pretty good idea and it should be fairly straightforward to implement. I'll have a look at it sometime soon.

Also, thanks for enjoying the mod :3

**Comment by killfrenzy96** [comment]
Implemented in version 1.0.26.
